Contact Us Page > Form and Get In Touch Header
Toronto-Tech-Mentoring/TTM-Gatsby pull request #103
Opened 2020-12-06 05:38 UTC by hanlinc27

2020-12-06 05:39 UTC, hanlinc27 commented
Oops the file diff is caused by running prettier

2020-12-06 05:45 UTC, BBoutet1 commented on gatsby-config.js
> +          `Poppins\:300,400,500,600,700,800,900`,
Please can you remove the second "Poppins" line

2020-12-06 05:48 UTC, hanlinc27 commented
I'm going to try to undo the linting on all the files and push up new changes because the diff is way too messy right now. The relevant page should be `ContactUsForm.js` though if anyone would like to take a look.

2020-12-06 05:58 UTC, BBoutet1 requested changes

2020-12-06 05:58 UTC, BBoutet1 commented on gatsby-config.js
> +          `Poppins\:300,400,500,600,700,800,900`,
```
          `Poppins\:300,400,500,600,700,800,900`,
```
Please @hanlinc27  can you remove the duplicate line?

2020-12-06 06:04 UTC, BBoutet1 approved these changes, later dismissed

2020-12-06 23:30 UTC, BBoutet1 commented
@hanlinc27 you'll need to fix the conflicts as "Volunteer/index.js" has been modified in the previous PR.

2020-12-07 01:52 UTC, dghazi12 commented
Just a couple of minor things - First, the cheetoh positioning is off/missing a cheetoh as per Figma. There is also a typo in the "fill in the form below.... " sentence. The word missing is "touch" 

PR: 

![Screen Shot 2020-12-06 at 8 48 20 PM](https://user-images.githubusercontent.com/59675897/101300691-64f90c80-3804-11eb-99a4-5838cf518ee1.png)

FIGMA : 

![Screen Shot 2020-12-06 at 8 44 45 PM](https://user-images.githubusercontent.com/59675897/101300574-09c71a00-3804-11eb-8738-c61850532fd7.png)

Otherwise, looks pretty good!!

2020-12-07 20:37 UTC, merged